-- Add 'suspension' (הרחקה) as a new disciplinary type, distinct from
-- 'ejection' (גירוש) which is single-game expulsion. Suspension is a
-- multi-game block that lasts up to a specific round.
--
-- Also adds `suspension_until_round`: the LAST round the suspension
-- applies to. Meaningful only for type='suspension'; NULL for other types.

DO $$
DECLARE c_name text;
BEGIN
  -- Drop whatever the existing CHECK on `type` is called. The constraint
  -- name is auto-generated by Postgres, so look it up first.
  FOR c_name IN
    SELECT conname
    FROM pg_constraint
    WHERE conrelid = 'public.disciplinary_records'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) ILIKE '%type%'
  LOOP
    EXECUTE format('ALTER TABLE public.disciplinary_records DROP CONSTRAINT %I', c_name);
  END LOOP;
END $$;

ALTER TABLE public.disciplinary_records
  ADD CONSTRAINT disciplinary_records_type_check
  CHECK (type IN ('technical', 'unsportsmanlike', 'ejection', 'suspension'));

ALTER TABLE public.disciplinary_records
  ADD COLUMN IF NOT EXISTS suspension_until_round int;

COMMENT ON COLUMN public.disciplinary_records.suspension_until_round IS
  'For type=suspension only: the last round (inclusive) the suspension applies to.';
